name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.4'
      - name: Run java unit tests
        working-directory: cli
        run: ./gradlew test
      - run: npm install
        working-directory: vscode
      - name: Run js unit tests
        working-directory: vscode
        run: npm test
